version: "3.8"
services:
  redis:
    image: redis:alpine
    env_file: .env
    container_name: redis
    ports:
      - "6379:6379"
  # url-shortener:
  #   env_file: .env
  #   container_name: url-shortener
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
